const usersData = [
  {
    name: "John Doe",
    company: "Company A",
    email: "john.doe@example.com",
    username: "johndoe",
    password: "password123",
    website: "https://johndoe.com",
    category: "Technology",
    netfunding: 1000000,
    mentor: true,
  },
  {
    name: "Jane Smith",
    company: "Company B",
    email: "jane.smith@example.com",
    username: "janesmith",
    password: "password123",
    website: "https://janesmith.com",
    category: "Healthcare",
    netfunding: 2000000,
    mentor: false,
  },
  // Add 8 more users with similar structure
  {
    name: "Alice Johnson",
    company: "Company C",
    email: "alice.johnson@example.com",
    username: "alicejohnson",
    password: "password123",
    website: "https://alicejohnson.com",
    category: "Finance",
    netfunding: 1500000,
    mentor: true,
  },
  {
    name: "Bob Brown",
    company: "Company D",
    email: "bob.brown@example.com",
    username: "bobbrown",
    password: "password123",
    website: "https://bobbrown.com",
    category: "Education",
    netfunding: 500000,
    mentor: false,
  },
  {
    name: "Charlie Davis",
    company: "Company E",
    email: "charlie.davis@example.com",
    username: "charliedavis",
    password: "password123",
    website: "https://charliedavis.com",
    category: "Technology",
    netfunding: 3000000,
    mentor: true,
  },
  {
    name: "Diana Evans",
    company: "Company F",
    email: "diana.evans@example.com",
    username: "dianaevans",
    password: "password123",
    website: "https://dianaevans.com",
    category: "Healthcare",
    netfunding: 2500000,
    mentor: false,
  },
  {
    name: "Ethan Foster",
    company: "Company G",
    email: "ethan.foster@example.com",
    username: "ethanfoster",
    password: "password123",
    website: "https://ethanfoster.com",
    category: "Finance",
    netfunding: 1200000,
    mentor: true,
  },
  {
    name: "Fiona Green",
    company: "Company H",
    email: "fiona.green@example.com",
    username: "fionagreen",
    password: "password123",
    website: "https://fionagreen.com",
    category: "Education",
    netfunding: 800000,
    mentor: false,
  },
  {
    name: "George Harris",
    company: "Company I",
    email: "george.harris@example.com",
    username: "georgeharris",
    password: "password123",
    website: "https://georgeharris.com",
    category: "Technology",
    netfunding: 4000000,
    mentor: true,
  },
  {
    name: "Hannah White",
    company: "Company J",
    email: "hannah.white@example.com",
    username: "hannahwhite",
    password: "password123",
    website: "https://hannahwhite.com",
    category: "Healthcare",
    netfunding: 3500000,
    mentor: false,
  },
];

export default usersData;
